const resourceData = [
    {
        category: "Research Papers",
        icon: "📄",
        items: [
            {
                id: "paper1",
                title: "Bioelectronic Medicine",
                subtitle: "Neural Recording and Stimulation",
                source: "Nature Reviews | 2024 | 12 Pages",
                description: "A comprehensive review of bioelectronic approaches to neural recording and stimulation techniques used in modern medicine.",
                content: {
                    sections: [
                        {
                            heading: "1. Abstract",
                            body: "Bioelectronic medicine represents a paradigm shift in modern healthcare, moving beyond traditional pharmaceutical interventions toward direct, precise modulation of the body's neural circuitry. By harnessing the language of the nervous system—electrical action potentials and synaptic transmission—bioelectronic devices can sense physiological distress, interpret biological signals in real-time, and deliver therapeutic electrical, magnetic, or optogenetic stimulation to specific neural targets."
                        },
                        {
                            heading: "2. The History of Neural Modulation",
                            body: "The conceptual foundation of bioelectronic medicine dates back to Luigi Galvani's 18th-century experiments demonstrating that electrical stimulation could evoke muscle contractions in frog legs. However, the modern era of clinical bioelectronics truly began with the invention of the cardiac pacemaker in the 1950s and the cochlear implant in the 1970s."
                        },
                        {
                            heading: "3. Foundational Physics of Neural Recording",
                            body: "Neural recording involves capturing the minute electrical potentials generated by the synchronized flux of ions across neuronal cell membranes. When a neuron fires an action potential, voltage-gated sodium channels open, allowing an influx of Na+ ions that rapidly depolarizes the membrane. This creates a transient electrical field in the extracellular space."
                        },
                        {
                            heading: "4. Electrode-Tissue Interface Chemistry",
                            body: "The junction between the metallic recording electrode and the biological tissue represents a complex electrochemical interface. When an electrode, typically composed of noble metals like platinum, iridium, or gold, is submerged in the conductive, ion-rich cerebrospinal fluid or interstitial fluid, a Helmholtz double-layer capacitance forms instantly at the boundary."
                        },
                        {
                            heading: "5. Monopolar Recording Architectures",
                            body: "In a standard monopolar recording configuration, the electrical potential is measured between a single 'active' exploring electrode positioned adjacent to the target neural population and a distant 'reference' electrode considered to be electrically neutral. Monopolar recordings offer a broad, macroscopic view of neural activity."
                        },
                        {
                            heading: "6. Bipolar Recording Architectures",
                            body: "Bipolar recording paradigms utilize two closely spaced active electrodes, measuring the differential voltage between them rather than the absolute voltage against a distant referent. This differential approach fundamentally alters the nature of the recorded signal, exhibiting superior Signal-to-Noise Ratios (SNR) in electrically hazardous environments."
                        }
                    ]
                }
            },
            {
                id: "paper2",
                title: "Electrode Configuration Strategies",
                subtitle: "Clinical Settings & Analysis",
                source: "IEEE Transactions on Biomedical Engineering | 2023 | 11 Pages",
                description: "Comparative analysis of monopolar vs bipolar electrode configurations in clinical biomedical signal recording.",
                content: {
                    sections: [
                        {
                            heading: "1. Introduction to Signal Acquisition",
                            body: "The integrity of any biomedical diagnostic workflow rests entirely upon the physical interface between the patient and the amplifier. The electrode configuration strategy dictates how electrical potentials are sampled, filtered, and geographically referenced."
                        },
                        {
                            heading: "2. The Monopolar Paradigm",
                            body: "Monopolar derivations, often referred to as referential montages in clinical electrophysiology, hinge on the concept of measuring the absolute electrical potential at a highly specific 'active' location against a 'neutral' physiological ground."
                        },
                        {
                            heading: "3. The Bipolar Paradigm: Surgical Precision",
                            body: "Bipolar electrode configurations abandon the pursuit of absolute voltage against a distant ground. Instead, a bipolar montage measures the precise, highly localized potential difference between two tightly clustered active electrodes sitting adjacent to one another over the target tissue."
                        }
                    ]
                }
            },
            {
                id: "paper3",
                title: "Neural Signal Processing Methods",
                subtitle: "Advanced Computational Decoding",
                source: "Journal of Neural Engineering | 2024 | 14 Pages",
                description: "Advanced computational methods for filtering, decoding, and interpreting high-density biological signals from the human nervous system.",
                content: {
                    sections: [
                        {
                            heading: "1. The Digital Foundation of Bioelectricity",
                            body: "The human nervous system is fundamentally an analog transmission network. Neural signal processing encompasses the entire mathematical pipeline required to cross this analog-to-digital divide: amplification, ADC, filtering, artifact rejection, and decoding."
                        },
                        {
                            heading: "2. The Fast Fourier Transform (FFT)",
                            body: "The Fast Fourier Transform calculates how much power exists within every individual frequency band of the recorded signal. It is the bedrock of quantitative EEG and is vital for designing digital filters."
                        },
                        {
                            heading: "3. Digital Filtering: Isolating the Signal",
                            body: "Digital filtering is the computational act of deliberately suppressing unwanted frequency bands while preserving diagnostic biological frequencies. Filters include low-pass, high-pass, band-pass, and notch types."
                        }
                    ]
                }
            }
        ]
    },
    {
        category: "Video Tutorials",
        icon: "🎥",
        items: [
            {
                id: "video1",
                title: "Electrode Setup Guide",
                subtitle: "Step-by-Step Preparation",
                source: "Video Tutorial Notes | Dr. Sarah Johnson | 15:24",
                description: "Companion notes for the Electrode Setup Guide video tutorial covering proper setup procedures for various electrode types.",
                content: {
                    sections: [
                        {
                            heading: "1. Equipment Preparation",
                            body: "Gather all necessary supplies: electrodes (surface, needle, or depth), conductive gel, skin prep materials (alcohol, abrasive pads), and the recording system. Verify calibration and function."
                        },
                        {
                            heading: "2. Patient Preparation",
                            body: "Position the patient comfortably. Mark anatomical landmarks. Clean sites with alcohol to remove oils. Use gentle abrasion to reduce skin impedance below 5 kOhm."
                        }
                    ]
                }
            },
            {
                id: "video2",
                title: "Signal Quality Troubleshooting",
                subtitle: "Artifact Rejection Techniques",
                source: "Video Tutorial Notes | Prof. Michael Chen | 22:18",
                description: "Companion notes for the Signal Quality Troubleshooting video covering systematic approaches to diagnosing and fixing signal quality issues.",
                content: {
                    sections: [
                        {
                            heading: "1. Systematic Troubleshooting",
                            body: "Identify the problem: Is it all channels? Intermittent? character character characterize the artifact by frequency and amplitude. Apply targeted solutions and verify."
                        },
                        {
                            heading: "2. Environmental Noise",
                            body: "Evaluate for 50/60 Hz interference from lighting, nearby MRI equipment, or mobile phones. Ensure proper grounding and use shielded cables."
                        }
                    ]
                }
            }
        ]
    },
    {
        category: "Quick Reference Cards",
        icon: "📑",
        items: [
            {
                id: "card1",
                title: "Electrode Placement Guide",
                subtitle: "Anatomical Landmarks & Systems",
                source: "Quick Reference Card | BioElectrode AI",
                description: "A practical guide to proper electrode placement techniques for various biomedical signal recording applications.",
                content: {
                    sections: [
                        {
                            heading: "1. EEG (10-20 System)",
                            body: "Standard placement at 10% and 20% distances between Nasion, Inion, and Preauricular points. Common positions: Fp1, Fp2, C3, C4, O1, O2."
                        },
                        {
                            heading: "2. ECG (12-Lead)",
                            body: "Uses 10 electrodes: 4 limb (RA, LA, RL, LL) and 6 precordial (V1-V6). V1/V2 at 4th intercostal space."
                        }
                    ]
                }
            },
            {
                id: "card2",
                title: "Signal Interpretation Checklist",
                subtitle: "Systematic Analysis Protocol",
                source: "Quick Reference Card | BioElectrode AI",
                description: "A systematic checklist for interpreting biomedical signals in clinical and research settings.",
                content: {
                    sections: [
                        {
                            heading: "1. Quality Assessment",
                            body: "Evaluate amplitude range, baseline stability, and signal-to-noise ratio. Check for movement or muscle artifacts."
                        },
                        {
                            heading: "2. Frequency Analysis",
                            body: "Assess activity in standard bands: Delta (0.5-4Hz), Theta (4-8Hz), Alpha (8-13Hz), Beta (13-30Hz), Gamma (>30Hz)."
                        }
                    ]
                }
            },
            {
                id: "card3",
                title: "Troubleshooting Common Issues",
                subtitle: "Error Detection & Rectification",
                source: "Quick Reference Card | BioElectrode AI",
                description: "A practical guide to identifying and resolving common problems encountered during biomedical signal recording.",
                content: {
                    sections: [
                        {
                            heading: "1. High Impedance",
                            body: "Usually caused by poor skin prep or dry gel. Re-clean and re-apply gel to achieve <5 kOhm."
                        },
                        {
                            heading: "2. 60 Hz Interference",
                            body: "Ensure proper grounding and move cables away from power lines. Check if ground electrode is secure."
                        }
                    ]
                }
            }
        ]
    }
];
